import React from 'react';
import Head from "next/head";
import {NextPage} from "next";
import {ILayout} from "../types";
import Footer from "./Footer";

const Layout: NextPage<ILayout> = ({ children, title = 'ToDoList' }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {children}
            </main>

            <Footer/>
        </>
    );
};

export default Layout;