import React, {ReactNode} from 'react';
import Head from "next/head";
import {NextPage} from "next";
// import Footer from "./Footer";

interface ILayout {
    title?: string,
    children: ReactNode
}

const Layout: NextPage<ILayout> = ({ children, title = 'ToDoList' }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {children}
            </main>

            {/*<Footer/>*/}
        </>
    );
};

export default Layout;