import React, {ReactNode} from 'react';
import Head from "next/head";
import {NextPage} from "next";
import styles from "../styles/Home.module.css";
import Image from "next/image";

interface ILayout {
    title?: string,
    children: ReactNode
}

const Layout: NextPage<ILayout> = ({ children, title = 'ToDoList' }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {children}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </>
    );
};

export default Layout;